name: local_storage_todos_api
description: A Flutter implementation of the TodosApi that uses local storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  rxdart: ^0.27.6
  shared_preferences: ^2.4.0
  todos_api:
    path: ../todos_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
